import type { Locale } from './i18n';

/* App-CHROME strings for the course experience (nav, buttons, exam UI, paywall,
   account menu…). Distinct from the COURSE CONTENT catalog (i18n/<slug>.<m>.json,
   applied by lib/i18n-course.ts). Keys fall back to English if a locale lacks one.
   Client components read these via useUI() (see components/CourseLocale.tsx);
   server components call tUI(locale, key, vars). Some values contain inline
   <b>…</b> and are rendered via dangerouslySetInnerHTML at the call site. */

type Strings = Record<string, string>;

const en: Strings = {
  // nav / sidebar
  'nav.home': 'Home & progress',
  'nav.ipa': 'IPA guide',
  'nav.exam': 'The official exam',
  'nav.mock': 'Mock exam',
  'nav.glossary': 'Glossary',
  'nav.unit': 'Unit {n}',
  'nav.getFull': 'Get the full course',
  'nav.getCourse': 'Get the course',
  'nav.allCourses': 'All courses',
  'nav.account': 'Account & purchases',
  'nav.admin': 'Admin dashboard',
  'nav.myCourses': 'My courses & progress',
  'auth.login': 'Log in',
  'auth.signout': 'Sign out',
  'ui.explainedIn': 'Explained in',
  // a11y
  'a11y.locked': 'Locked',
  'a11y.expand': 'Expand course menu',
  'a11y.collapse': 'Collapse course menu',
  'a11y.courseNav': 'Course navigation',
  'a11y.courseHome': 'Course home',
  'a11y.allCourses': 'Verbadium — all courses',
  'a11y.courseMenu': 'Course menu',
  'a11y.accountMenu': 'Account menu',
  'a11y.close': 'Close',
  'a11y.playAudio': 'Play audio {n}',
  // exercises
  'ex.section': 'Exercises',
  'ex.done': '✓ done',
  'ex.tried': 'tried',
  'btn.check': 'Check answers',
  'btn.showCorrect': 'Show correct answers',
  'btn.showModel': 'Show model answer',
  'btn.showModels': 'Show model answers',
  'btn.showCatalan': 'Show the Catalan',
  'btn.retry': 'Retry',
  'sm.gotIt': '✓ I got it',
  'sm.notYet': '✗ Not yet',
  'sm.done': '✓ Done',
  'tf.true': 'True',
  'tf.false': 'False',
  'fb.accents': '✓ (check the accents!)',
  'score.perfect': 'perfecte!',
  'ph.inCatalan': '…in Catalan',
  'ph.inMeaning': '…in English',
  'ph.writeHere': 'Write here…',
  'chk.aloud': 'I said it aloud',
  // dashboard
  'dash.progress': 'Your progress',
  'dash.passed': '{passed} of {total} exercises passed',
  'dash.inProgress': '{n} in progress',
  'dash.continue': 'Continue · Unit {n}',
  'dash.start': 'Start the course · Unit 1',
  'dash.allDonePre': 'All units complete — time for the ',
  'dash.mockLink': 'mock exam',
  'dash.upNext': 'Up next: Unit {n} has unfinished exercises.',
  'dash.exercises': '{passed}/{total} exercises',
  'dash.mockAttempts': 'Mock exam attempts: {n} (last: {date})',
  'dash.mockNone': 'Mock exam not attempted yet.',
  'dash.resetAll': 'Reset all progress',
  'dash.resetConfirm': 'Reset ALL progress? This clears exercise results, the checklist and mock-exam history.',
  'dash.mockHistory': 'Mock exam history',
  'th.date': 'Date',
  'th.listening': 'Listening',
  'th.readingA': 'Reading A',
  'th.readingB': 'Reading B',
  'th.writing': 'Writing',
  'th.speaking': 'Speaking',
  // checklist
  'chklist.title': 'A1 self-assessment checklist',
  'chklist.intro': 'Tick what you can do confidently. All boxes ticked = you are ready to register for the exam.',
  // drawers
  'ipa.tab': 'IPA pronunciation reference',
  'ipa.tabShort': 'IPA /ə/',
  'ipa.quick': 'IPA quick reference',
  'ipa.full': 'Full guide',
  'glos.full': 'Full page',
  // buy
  'buy.opening': 'Opening checkout…',
  'buy.buy': 'Buy the course · {price}',
  'buy.errStart': 'Could not start checkout. Please try again.',
  'buy.errLoad': 'Could not load the checkout. Please try again.',
  'buy.errConn': 'Could not start checkout. Please check your connection and try again.',
  // paywall
  'pw.locked': 'LOCKED',
  'pw.partOfFull': '{what} is part of the full course',
  'pw.oneTime': 'One payment of {price} unlocks everything, forever: all {units} units, the mock exam with timers, the full glossary and progress tracking across your devices.',
  'pw.alreadyBought': 'Already bought it? Log in',
  'pw.notSure': 'Not sure yet?',
  'pw.tryFree': 'Try Unit {n} free',
  'pw.noAccount': '— no account needed.',
  'what.glossary': 'The glossary',
  'what.mock': 'The mock exam',
  // free-preview banner
  'banner.preview': 'You’re viewing the <b>free preview</b>. Your answers are saved on this device',
  'banner.previewKeep': ' — create an account to keep them',
  // mock exam
  'mock.head': 'Mock exam · A1',
  'mock.title': 'Full Practice Exam',
  'mock.conditions': 'Exam conditions',
  'mock.conditionsNote': ' — show per-paper timers (15 / 30 / 30 / 10 min). When time runs out the paper is marked “over time”, but you can finish.',
  'mock.p1title': 'Paper 1 · Comprensió oral (listening) — 15 min',
  'mock.p2title': 'Paper 2 · Comprensió lectora (reading) — 30 min',
  'mock.p3title': 'Paper 3 · Expressió escrita (writing) — 30 min',
  'mock.p4title': 'Paper 4 · Expressió oral (speaking) — 10 min',
  'mock.timerReset': 'Reset timer',
  'mock.timerStart': 'Start {mins}-min timer',
  'mock.p1note': 'The script is read aloud <b>twice</b> with a pause, using your browser’s Catalan voice. Don’t read it — just listen, then answer.',
  'mock.play': '▶ Play listening script (twice)',
  'mock.stop': '■ Stop',
  'mock.playP1': 'Playing — first reading…',
  'mock.playPause': 'Pause… second reading starts in 5 s',
  'mock.playP2': 'Playing — second reading…',
  'mock.showScript': 'Show script',
  'mock.taskA2': 'Task A — Read this notice and answer.',
  'mock.answers': 'Answers',
  'mock.showAnswers': 'Show answers',
  'mock.taskB2': 'Task B — Match each sign (1–5) to its meaning (a–e).',
  'mock.taskA3': 'Task A — Fill in this library-card application about yourself.',
  'mock.p3ph': 'Write your postcard here (35–45 words)…',
  'mock.words': 'Words:',
  'mock.model38': 'Model (38 words)',
  'mock.part1p4': 'Part 1 — Answer these aloud in full sentences (the examiner’s classic set):',
  'mock.modelP1': 'Model answers (Part 1)',
  'mock.roleSkeleton': 'Role-play skeleton',
  'mock.saveTitle': 'Save this attempt',
  'mock.saveNote': 'Finishes the sitting and stores the per-paper results (with today’s date) in your browser.',
  'mock.finishSave': 'Finish & save attempt',
  'mock.saved': 'Attempt saved.',
  'mock.history': 'Attempt history',
  'mock.noAttempts': 'No attempts saved yet.',
  'mock.thP1': 'P1 listening',
  'mock.thP2': 'P2 reading',
  'mock.thP3': 'P3 writing',
  'mock.thP4': 'P4 speaking',
  'mock.overTime': ' over time',
  'mock.selfPassed': 'self-passed',
  'mock.notYet': 'not yet',
  'mock.wordsAbbr': 'w.',
  'mock.aloud': 'aloud',
};

const es: Strings = {
  'nav.home': 'Inicio y progreso',
  'nav.ipa': 'Guía del AFI',
  'nav.exam': 'El examen oficial',
  'nav.mock': 'Examen de práctica',
  'nav.glossary': 'Glosario',
  'nav.unit': 'Unidad {n}',
  'nav.getFull': 'Consigue el curso completo',
  'nav.getCourse': 'Consigue el curso',
  'nav.allCourses': 'Todos los cursos',
  'nav.account': 'Cuenta y compras',
  'nav.admin': 'Panel de administración',
  'nav.myCourses': 'Mis cursos y progreso',
  'auth.login': 'Iniciar sesión',
  'auth.signout': 'Cerrar sesión',
  'ui.explainedIn': 'Explicado en',
  'a11y.locked': 'Bloqueado',
  'a11y.expand': 'Expandir el menú del curso',
  'a11y.collapse': 'Contraer el menú del curso',
  'a11y.courseNav': 'Navegación del curso',
  'a11y.courseHome': 'Inicio del curso',
  'a11y.allCourses': 'Verbadium — todos los cursos',
  'a11y.courseMenu': 'Menú del curso',
  'a11y.accountMenu': 'Menú de la cuenta',
  'a11y.close': 'Cerrar',
  'a11y.playAudio': 'Reproducir audio {n}',
  'ex.section': 'Ejercicios',
  'ex.done': '✓ hecho',
  'ex.tried': 'intentado',
  'btn.check': 'Comprobar respuestas',
  'btn.showCorrect': 'Ver las respuestas correctas',
  'btn.showModel': 'Ver respuesta modelo',
  'btn.showModels': 'Ver respuestas modelo',
  'btn.showCatalan': 'Ver el catalán',
  'btn.retry': 'Reintentar',
  'sm.gotIt': '✓ Lo tengo',
  'sm.notYet': '✗ Todavía no',
  'sm.done': '✓ Hecho',
  'tf.true': 'Verdadero',
  'tf.false': 'Falso',
  'fb.accents': '✓ (¡revisa los acentos!)',
  'score.perfect': '¡perfecto!',
  'ph.inCatalan': '…en catalán',
  'ph.inMeaning': '…en español',
  'ph.writeHere': 'Escribe aquí…',
  'chk.aloud': 'Lo dije en voz alta',
  'dash.progress': 'Tu progreso',
  'dash.passed': '{passed} de {total} ejercicios superados',
  'dash.inProgress': '{n} en curso',
  'dash.continue': 'Continuar · Unidad {n}',
  'dash.start': 'Empezar el curso · Unidad 1',
  'dash.allDonePre': 'Todas las unidades completas: hora del ',
  'dash.mockLink': 'examen de práctica',
  'dash.upNext': 'A continuación: la Unidad {n} tiene ejercicios sin terminar.',
  'dash.exercises': '{passed}/{total} ejercicios',
  'dash.mockAttempts': 'Intentos del examen de práctica: {n} (último: {date})',
  'dash.mockNone': 'Aún no has hecho el examen de práctica.',
  'dash.resetAll': 'Reiniciar todo el progreso',
  'dash.resetConfirm': '¿Reiniciar TODO el progreso? Esto borra los resultados de los ejercicios, la lista de verificación y el historial del examen de práctica.',
  'dash.mockHistory': 'Historial del examen de práctica',
  'th.date': 'Fecha',
  'th.listening': 'Comprensión auditiva',
  'th.readingA': 'Lectura A',
  'th.readingB': 'Lectura B',
  'th.writing': 'Expresión escrita',
  'th.speaking': 'Expresión oral',
  'chklist.title': 'Lista de autoevaluación A1',
  'chklist.intro': 'Marca lo que puedas hacer con confianza. Todas las casillas marcadas = estás listo para inscribirte en el examen.',
  'ipa.tab': 'Referencia de pronunciación AFI',
  'ipa.tabShort': 'AFI /ə/',
  'ipa.quick': 'Referencia rápida del AFI',
  'ipa.full': 'Guía completa',
  'glos.full': 'Página completa',
  'buy.opening': 'Abriendo el pago…',
  'buy.buy': 'Comprar el curso · {price}',
  'buy.errStart': 'No se pudo iniciar el pago. Inténtalo de nuevo.',
  'buy.errLoad': 'No se pudo cargar el pago. Inténtalo de nuevo.',
  'buy.errConn': 'No se pudo iniciar el pago. Comprueba tu conexión e inténtalo de nuevo.',
  'pw.locked': 'BLOQUEADO',
  'pw.partOfFull': '{what} forma parte del curso completo',
  'pw.oneTime': 'Un único pago de {price} lo desbloquea todo, para siempre: las {units} unidades, el examen de práctica con cronómetros, el glosario completo y el seguimiento del progreso en todos tus dispositivos.',
  'pw.alreadyBought': '¿Ya lo compraste? Inicia sesión',
  'pw.notSure': '¿Aún no lo tienes claro?',
  'pw.tryFree': 'Prueba la Unidad {n} gratis',
  'pw.noAccount': '— sin necesidad de cuenta.',
  'what.glossary': 'El glosario',
  'what.mock': 'El examen de práctica',
  'banner.preview': 'Estás viendo la <b>vista previa gratuita</b>. Tus respuestas se guardan en este dispositivo',
  'banner.previewKeep': ' — crea una cuenta para conservarlas',
  'mock.head': 'Examen de práctica · A1',
  'mock.title': 'Examen de práctica completo',
  'mock.conditions': 'Condiciones de examen',
  'mock.conditionsNote': ' — muestra cronómetros por prueba (15 / 30 / 30 / 10 min). Cuando se acaba el tiempo, la prueba se marca como “fuera de tiempo”, pero puedes terminar.',
  'mock.p1title': 'Prueba 1 · Comprensió oral (comprensión auditiva) — 15 min',
  'mock.p2title': 'Prueba 2 · Comprensió lectora (comprensión lectora) — 30 min',
  'mock.p3title': 'Prueba 3 · Expressió escrita (expresión escrita) — 30 min',
  'mock.p4title': 'Prueba 4 · Expressió oral (expresión oral) — 10 min',
  'mock.timerReset': 'Reiniciar cronómetro',
  'mock.timerStart': 'Iniciar cronómetro de {mins} min',
  'mock.p1note': 'El audio se reproduce <b>dos veces</b> con una pausa, usando la voz catalana de tu navegador. No lo leas: solo escucha y luego responde.',
  'mock.play': '▶ Reproducir el audio (dos veces)',
  'mock.stop': '■ Detener',
  'mock.playP1': 'Reproduciendo — primera lectura…',
  'mock.playPause': 'Pausa… la segunda lectura empieza en 5 s',
  'mock.playP2': 'Reproduciendo — segunda lectura…',
  'mock.showScript': 'Ver la transcripción',
  'mock.taskA2': 'Tarea A — Lee este aviso y responde.',
  'mock.answers': 'Respuestas',
  'mock.showAnswers': 'Ver respuestas',
  'mock.taskB2': 'Tarea B — Relaciona cada cartel (1–5) con su significado (a–e).',
  'mock.taskA3': 'Tarea A — Rellena esta solicitud de carné de biblioteca sobre ti.',
  'mock.p3ph': 'Escribe tu postal aquí (35–45 palabras)…',
  'mock.words': 'Palabras:',
  'mock.model38': 'Modelo (38 palabras)',
  'mock.part1p4': 'Parte 1 — Responde en voz alta con frases completas (el repertorio clásico del examinador):',
  'mock.modelP1': 'Respuestas modelo (Parte 1)',
  'mock.roleSkeleton': 'Esquema del juego de rol',
  'mock.saveTitle': 'Guarda este intento',
  'mock.saveNote': 'Finaliza la sesión y guarda los resultados por prueba (con la fecha de hoy) en tu navegador.',
  'mock.finishSave': 'Finalizar y guardar intento',
  'mock.saved': 'Intento guardado.',
  'mock.history': 'Historial de intentos',
  'mock.noAttempts': 'Aún no hay intentos guardados.',
  'mock.thP1': 'P1 audición',
  'mock.thP2': 'P2 lectura',
  'mock.thP3': 'P3 escritura',
  'mock.thP4': 'P4 expresión oral',
  'mock.overTime': ' fuera de tiempo',
  'mock.selfPassed': 'autoaprobado',
  'mock.notYet': 'todavía no',
  'mock.wordsAbbr': 'pal.',
  'mock.aloud': 'en voz alta',
};

export const UI: Record<Locale, Strings> = { en, es, ca: en, fr: en, ru: en };

/** Translate a chrome key for a locale, with {placeholder} interpolation and
    English fallback. */
export function tUI(locale: Locale, key: string, vars?: Record<string, string | number>): string {
  let s = UI[locale]?.[key] ?? en[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}
