import type { Locale } from './i18n';
import { interpolate, type Strings, type BuyLabels } from './ui-runtime';

/* App-CHROME strings for the course experience (nav, buttons, exam UI, paywall,
   account menu…). Distinct from the COURSE CONTENT catalog (i18n/<slug>.<m>.json,
   applied by lib/i18n-course.ts). Keys fall back to English if a locale lacks one.
   This module is SERVER-side: client components get the active locale's dict via
   uiDict() handed through CourseLocaleProvider, then read it with useUI() — so
   only one locale's strings ship to the browser, not the whole map.
   Some values contain inline <b>…</b> rendered via dangerouslySetInnerHTML. */

const en: Strings = {
  // nav / sidebar
  'nav.home': 'Home & progress',
  'nav.ipa': 'IPA guide',
  'nav.exam': 'The official exam',
  'nav.mock': 'Mock exam',
  'nav.glossary': 'Glossary',
  'nav.unit': 'Unit {n}',
  'nav.getFull': 'Get the full course',
  'nav.getCourse': 'Get the course',
  'nav.allCourses': 'All courses',
  'nav.account': 'Account & purchases',
  'nav.admin': 'Admin dashboard',
  'nav.myCourses': 'My courses & progress',
  'auth.login': 'Log in',
  'auth.signout': 'Sign out',
  'ui.explainedIn': 'Explained in',
  // a11y
  'a11y.locked': 'Locked',
  'a11y.expand': 'Expand course menu',
  'a11y.collapse': 'Collapse course menu',
  'a11y.courseNav': 'Course navigation',
  'a11y.courseHome': 'Course home',
  'a11y.allCourses': 'Verbadium — all courses',
  'a11y.courseMenu': 'Course menu',
  'a11y.accountMenu': 'Account menu',
  'a11y.close': 'Close',
  'a11y.playAudio': 'Play audio {n}',
  // exercises
  'ex.section': 'Exercises',
  'ex.modelAnswer': 'Model answer',
  'ex.note': 'Note',
  'ex.personalNote': 'Personal answers — fill it in as exam practice.',
  'glos.heading': 'Glossary — every word in this course',
  'glos.intro': 'Alphabetical (articles ignored). U = the unit where the word is first taught. Pronunciations are Central Catalan, IPA. Click a column header to sort; click 🔊 to hear the word.',
  'glos.searchPh': 'Search the glossary…',
  'glos.entries': 'entries',
  'glos.listen': 'Listen',
  'glos.subject': 'Catalan',
  'glos.ipa': 'IPA',
  'glos.unitCol': 'U.',
  'ex.done': '✓ done',
  'ex.tried': 'tried',
  'btn.check': 'Check answers',
  'btn.showCorrect': 'Show correct answers',
  'btn.showModel': 'Show model answer',
  'btn.showModels': 'Show model answers',
  'btn.showCatalan': 'Show the Catalan',
  'btn.retry': 'Retry',
  'sm.gotIt': '✓ I got it',
  'sm.notYet': '✗ Not yet',
  'sm.done': '✓ Done',
  'tf.true': 'True',
  'tf.false': 'False',
  'fb.accents': '✓ (check the accents!)',
  'score.perfect': 'perfecte!',
  'ph.inCatalan': '…in Catalan',
  'ph.inMeaning': '…in English',
  'ph.writeHere': 'Write here…',
  'chk.aloud': 'I said it aloud',
  // dashboard
  'dash.progress': 'Your progress',
  'dash.passed': '{passed} of {total} exercises passed',
  'dash.inProgress': '{n} in progress',
  'dash.continue': 'Continue · Unit {n}',
  'dash.start': 'Start the course · Unit 1',
  'dash.allDonePre': 'All units complete — time for the ',
  'dash.mockLink': 'mock exam',
  'dash.upNext': 'Up next: Unit {n} has unfinished exercises.',
  'dash.exercises': '{passed}/{total} exercises',
  'dash.mockAttempts': 'Mock exam attempts: {n} (last: {date})',
  'dash.mockNone': 'Mock exam not attempted yet.',
  'dash.resetAll': 'Reset all progress',
  'dash.resetConfirm': 'Reset ALL progress? This clears exercise results, the checklist and mock-exam history.',
  'dash.mockHistory': 'Mock exam history',
  'th.date': 'Date',
  'th.listening': 'Listening',
  'th.readingA': 'Reading A',
  'th.readingB': 'Reading B',
  'th.writing': 'Writing',
  'th.speaking': 'Speaking',
  // checklist
  'chklist.title': 'A1 self-assessment checklist',
  'chklist.intro': 'Tick what you can do confidently. All boxes ticked = you are ready to register for the exam.',
  // drawers
  'ipa.tab': 'IPA pronunciation reference',
  'ipa.tabShort': 'IPA /ə/',
  'ipa.quick': 'IPA quick reference',
  'ipa.full': 'Full guide',
  'glos.full': 'Full page',
  // buy
  'buy.opening': 'Opening checkout…',
  'buy.buy': 'Buy the course · {price}',
  'buy.errStart': 'Could not start checkout. Please try again.',
  'buy.errLoad': 'Could not load the checkout. Please try again.',
  'buy.errConn': 'Could not start checkout. Please check your connection and try again.',
  // paywall
  'pw.locked': 'LOCKED',
  'pw.partOfFull': '{what} is part of the full course',
  'pw.oneTime': 'One payment of {price} unlocks everything, forever: all {units} units, the mock exam with timers, the full glossary and progress tracking across your devices.',
  'pw.alreadyBought': 'Already bought it? Log in',
  'pw.notSure': 'Not sure yet?',
  'pw.tryFree': 'Try Unit {n} free',
  'pw.noAccount': '— no account needed.',
  'what.glossary': 'The glossary',
  'what.mock': 'The mock exam',
  // free-preview banner
  'banner.preview': 'You’re viewing the <b>free preview</b>. Your answers are saved on this device',
  'banner.previewKeep': ' — create an account to keep them',
  // mock exam
  'mock.head': 'Mock exam · A1',
  'mock.title': 'Full Practice Exam',
  'mock.conditions': 'Exam conditions',
  'mock.conditionsNote': ' — show per-paper timers (15 / 30 / 30 / 10 min). When time runs out the paper is marked “over time”, but you can finish.',
  'mock.p1title': 'Paper 1 · Comprensió oral (listening) — 15 min',
  'mock.p2title': 'Paper 2 · Comprensió lectora (reading) — 30 min',
  'mock.p3title': 'Paper 3 · Expressió escrita (writing) — 30 min',
  'mock.p4title': 'Paper 4 · Expressió oral (speaking) — 10 min',
  'mock.timerReset': 'Reset timer',
  'mock.timerStart': 'Start {mins}-min timer',
  'mock.p1note': 'The script is read aloud <b>twice</b> with a pause, using your browser’s Catalan voice. Don’t read it — just listen, then answer.',
  'mock.play': '▶ Play listening script (twice)',
  'mock.stop': '■ Stop',
  'mock.playP1': 'Playing — first reading…',
  'mock.playPause': 'Pause… second reading starts in 5 s',
  'mock.playP2': 'Playing — second reading…',
  'mock.showScript': 'Show script',
  'mock.taskA2': 'Task A — Read this notice and answer.',
  'mock.answers': 'Answers',
  'mock.showAnswers': 'Show answers',
  'mock.taskB2': 'Task B — Match each sign (1–5) to its meaning (a–e).',
  'mock.taskA3': 'Task A — Fill in this library-card application about yourself.',
  'mock.p3ph': 'Write your postcard here (35–45 words)…',
  'mock.words': 'Words:',
  'mock.model38': 'Model (38 words)',
  'mock.part1p4': 'Part 1 — Answer these aloud in full sentences (the examiner’s classic set):',
  'mock.modelP1': 'Model answers (Part 1)',
  'mock.roleSkeleton': 'Role-play skeleton',
  'mock.saveTitle': 'Save this attempt',
  'mock.saveNote': 'Finishes the sitting and stores the per-paper results (with today’s date) in your browser.',
  'mock.finishSave': 'Finish & save attempt',
  'mock.saved': 'Attempt saved.',
  'mock.history': 'Attempt history',
  'mock.noAttempts': 'No attempts saved yet.',
  'mock.thP1': 'P1 listening',
  'mock.thP2': 'P2 reading',
  'mock.thP3': 'P3 writing',
  'mock.thP4': 'P4 speaking',
  'mock.overTime': ' over time',
  'mock.selfPassed': 'self-passed',
  'mock.notYet': 'not yet',
  'mock.wordsAbbr': 'w.',
  'mock.aloud': 'aloud',
};

const es: Strings = {
  "nav.home": "Inicio y progreso",
  "nav.ipa": "Guía del AFI",
  "nav.exam": "El examen oficial",
  "nav.mock": "Examen de práctica",
  "nav.glossary": "Glosario",
  "nav.unit": "Unidad {n}",
  "nav.getFull": "Consigue el curso completo",
  "nav.getCourse": "Consigue el curso",
  "nav.allCourses": "Todos los cursos",
  "nav.account": "Cuenta y compras",
  "nav.admin": "Panel de administración",
  "nav.myCourses": "Mis cursos y progreso",
  "auth.login": "Iniciar sesión",
  "auth.signout": "Cerrar sesión",
  "ui.explainedIn": "Explicado en",
  "a11y.locked": "Bloqueado",
  "a11y.expand": "Expandir el menú del curso",
  "a11y.collapse": "Contraer el menú del curso",
  "a11y.courseNav": "Navegación del curso",
  "a11y.courseHome": "Inicio del curso",
  "a11y.allCourses": "Verbadium — todos los cursos",
  "a11y.courseMenu": "Menú del curso",
  "a11y.accountMenu": "Menú de la cuenta",
  "a11y.close": "Cerrar",
  "a11y.playAudio": "Reproducir audio {n}",
  "ex.section": "Ejercicios",
  "ex.modelAnswer": "Respuesta modelo",
  "ex.note": "Nota",
  "ex.personalNote": "Respuestas personales: complétalas como práctica para el examen.",
  "glos.heading": "Glosario: todas las palabras del curso",
  "glos.intro": "Por orden alfabético (sin tener en cuenta los artículos). U = la unidad donde aparece la palabra por primera vez. Las pronunciaciones son en catalán central, AFI. Haz clic en una cabecera de columna para ordenar; haz clic en 🔊 para oír la palabra.",
  "glos.searchPh": "Busca en el glosario…",
  "glos.entries": "entradas",
  "glos.listen": "Escuchar",
  "glos.subject": "Catalán",
  "glos.ipa": "AFI",
  "glos.unitCol": "U.",
  "ex.done": "✓ hecho",
  "ex.tried": "intentado",
  "btn.check": "Comprobar respuestas",
  "btn.showCorrect": "Ver las respuestas correctas",
  "btn.showModel": "Ver respuesta modelo",
  "btn.showModels": "Ver respuestas modelo",
  "btn.showCatalan": "Ver el catalán",
  "btn.retry": "Reintentar",
  "sm.gotIt": "✓ Lo tengo",
  "sm.notYet": "✗ Todavía no",
  "sm.done": "✓ Hecho",
  "tf.true": "Verdadero",
  "tf.false": "Falso",
  "fb.accents": "✓ (¡revisa los acentos!)",
  "score.perfect": "perfecte!",
  "ph.inCatalan": "…en catalán",
  "ph.inMeaning": "…en español",
  "ph.writeHere": "Escribe aquí…",
  "chk.aloud": "Lo dije en voz alta",
  "dash.progress": "Tu progreso",
  "dash.passed": "{passed} de {total} ejercicios superados",
  "dash.inProgress": "{n} en curso",
  "dash.continue": "Continuar · Unidad {n}",
  "dash.start": "Empezar el curso · Unidad 1",
  "dash.allDonePre": "Todas las unidades completas: hora del ",
  "dash.mockLink": "examen de práctica",
  "dash.upNext": "A continuación: la Unidad {n} tiene ejercicios sin terminar.",
  "dash.exercises": "{passed}/{total} ejercicios",
  "dash.mockAttempts": "Intentos del examen de práctica: {n} (último: {date})",
  "dash.mockNone": "Aún no has hecho el examen de práctica.",
  "dash.resetAll": "Reiniciar todo el progreso",
  "dash.resetConfirm": "¿Reiniciar TODO el progreso? Esto borra los resultados de los ejercicios, la lista de autoevaluación y el historial del examen de práctica.",
  "dash.mockHistory": "Historial del examen de práctica",
  "th.date": "Fecha",
  "th.listening": "Comprensión auditiva",
  "th.readingA": "Lectura A",
  "th.readingB": "Lectura B",
  "th.writing": "Expresión escrita",
  "th.speaking": "Expresión oral",
  "chklist.title": "Lista de autoevaluación A1",
  "chklist.intro": "Marca lo que puedas hacer con confianza. Todas las casillas marcadas = estás listo para inscribirte en el examen.",
  "ipa.tab": "Referencia de pronunciación AFI",
  "ipa.tabShort": "AFI /ə/",
  "ipa.quick": "Referencia rápida del AFI",
  "ipa.full": "Guía completa",
  "glos.full": "Página completa",
  "buy.opening": "Abriendo el pago…",
  "buy.buy": "Comprar el curso · {price}",
  "buy.errStart": "No se pudo iniciar el pago. Inténtalo de nuevo.",
  "buy.errLoad": "No se pudo cargar el pago. Inténtalo de nuevo.",
  "buy.errConn": "No se pudo iniciar el pago. Comprueba tu conexión e inténtalo de nuevo.",
  "pw.locked": "BLOQUEADO",
  "pw.partOfFull": "{what} forma parte del curso completo",
  "pw.oneTime": "Un único pago de {price} lo desbloquea todo, para siempre: las {units} unidades, el examen de práctica con cronómetros, el glosario completo y el seguimiento del progreso en todos tus dispositivos.",
  "pw.alreadyBought": "¿Ya lo compraste? Inicia sesión",
  "pw.notSure": "¿Aún no lo tienes claro?",
  "pw.tryFree": "Prueba la Unidad {n} gratis",
  "pw.noAccount": "— sin necesidad de cuenta.",
  "what.glossary": "El glosario",
  "what.mock": "El examen de práctica",
  "banner.preview": "Estás viendo la <b>vista previa gratuita</b>. Tus respuestas se guardan en este dispositivo",
  "banner.previewKeep": " — crea una cuenta para conservarlas",
  "mock.head": "Examen de práctica · A1",
  "mock.title": "Examen de práctica completo",
  "mock.conditions": "Condiciones de examen",
  "mock.conditionsNote": " — muestra cronómetros por prueba (15 / 30 / 30 / 10 min). Cuando se acaba el tiempo, la prueba se marca como “fuera de tiempo”, pero puedes terminar.",
  "mock.p1title": "Prueba 1 · Comprensió oral (comprensión auditiva) — 15 min",
  "mock.p2title": "Prueba 2 · Comprensió lectora (comprensión lectora) — 30 min",
  "mock.p3title": "Prueba 3 · Expressió escrita (expresión escrita) — 30 min",
  "mock.p4title": "Prueba 4 · Expressió oral (expresión oral) — 10 min",
  "mock.timerReset": "Reiniciar cronómetro",
  "mock.timerStart": "Iniciar cronómetro de {mins} min",
  "mock.p1note": "El audio se reproduce <b>dos veces</b> con una pausa, usando la voz catalana de tu navegador. No lo leas: solo escucha y luego responde.",
  "mock.play": "▶ Reproducir el audio (dos veces)",
  "mock.stop": "■ Detener",
  "mock.playP1": "Reproduciendo — primera lectura…",
  "mock.playPause": "Pausa… la segunda lectura empieza en 5 s",
  "mock.playP2": "Reproduciendo — segunda lectura…",
  "mock.showScript": "Ver la transcripción",
  "mock.taskA2": "Tarea A — Lee este aviso y responde.",
  "mock.answers": "Respuestas",
  "mock.showAnswers": "Ver respuestas",
  "mock.taskB2": "Tarea B — Relaciona cada cartel (1–5) con su significado (a–e).",
  "mock.taskA3": "Tarea A — Rellena esta solicitud de carné de biblioteca con tus datos.",
  "mock.p3ph": "Escribe tu postal aquí (35–45 palabras)…",
  "mock.words": "Palabras:",
  "mock.model38": "Modelo (38 palabras)",
  "mock.part1p4": "Parte 1 — Responde en voz alta con frases completas (el repertorio clásico del examinador):",
  "mock.modelP1": "Respuestas modelo (Parte 1)",
  "mock.roleSkeleton": "Esquema del juego de rol",
  "mock.saveTitle": "Guarda este intento",
  "mock.saveNote": "Finaliza la sesión y guarda los resultados por prueba (con la fecha de hoy) en tu navegador.",
  "mock.finishSave": "Finalizar y guardar intento",
  "mock.saved": "Intento guardado.",
  "mock.history": "Historial de intentos",
  "mock.noAttempts": "Aún no hay intentos guardados.",
  "mock.thP1": "P1 audición",
  "mock.thP2": "P2 lectura",
  "mock.thP3": "P3 escritura",
  "mock.thP4": "P4 expresión oral",
  "mock.overTime": " fuera de tiempo",
  "mock.selfPassed": "autoaprobado",
  "mock.notYet": "todavía no",
  "mock.wordsAbbr": "pal.",
  "mock.aloud": "en voz alta",
};

const fr: Strings = {
  "nav.home": "Accueil et progression",
  "nav.ipa": "Guide API",
  "nav.exam": "L’examen officiel",
  "nav.mock": "Examen blanc",
  "nav.glossary": "Glossaire",
  "nav.unit": "Unité {n}",
  "nav.getFull": "Obtenir le cours complet",
  "nav.getCourse": "Obtenir le cours",
  "nav.allCourses": "Tous les cours",
  "nav.account": "Compte et achats",
  "nav.admin": "Tableau de bord admin",
  "nav.myCourses": "Mes cours et progression",
  "auth.login": "Se connecter",
  "auth.signout": "Se déconnecter",
  "ui.explainedIn": "Expliqué en",
  "a11y.locked": "Verrouillé",
  "a11y.expand": "Déplier le menu du cours",
  "a11y.collapse": "Replier le menu du cours",
  "a11y.courseNav": "Navigation du cours",
  "a11y.courseHome": "Accueil du cours",
  "a11y.allCourses": "Verbadium — tous les cours",
  "a11y.courseMenu": "Menu du cours",
  "a11y.accountMenu": "Menu du compte",
  "a11y.close": "Fermer",
  "a11y.playAudio": "Lire l’audio {n}",
  "ex.section": "Exercices",
  "ex.modelAnswer": "Réponse modèle",
  "ex.note": "Remarque",
  "ex.personalNote": "Réponses personnelles : complétez-les pour vous entraîner à l’examen.",
  "glos.heading": "Glossaire : tous les mots du cours",
  "glos.intro": "Par ordre alphabétique (articles ignorés). U = l’unité où le mot est introduit pour la première fois. Les prononciations sont en catalan central, API. Cliquez sur un en-tête de colonne pour trier ; cliquez sur 🔊 pour entendre le mot.",
  "glos.searchPh": "Rechercher dans le glossaire…",
  "glos.entries": "entrées",
  "glos.listen": "Écouter",
  "glos.subject": "Catalan",
  "glos.ipa": "API",
  "glos.unitCol": "U.",
  "ex.done": "✓ fait",
  "ex.tried": "essayé",
  "btn.check": "Vérifier les réponses",
  "btn.showCorrect": "Afficher les bonnes réponses",
  "btn.showModel": "Afficher la réponse modèle",
  "btn.showModels": "Afficher les réponses modèles",
  "btn.showCatalan": "Afficher le catalan",
  "btn.retry": "Réessayer",
  "sm.gotIt": "✓ J’ai compris",
  "sm.notYet": "✗ Pas encore",
  "sm.done": "✓ Terminé",
  "tf.true": "Vrai",
  "tf.false": "Faux",
  "fb.accents": "✓ (attention aux accents !)",
  "score.perfect": "perfecte!",
  "ph.inCatalan": "…en catalan",
  "ph.inMeaning": "…en français",
  "ph.writeHere": "Écrivez ici…",
  "chk.aloud": "Je l’ai dit à voix haute",
  "dash.progress": "Votre progression",
  "dash.passed": "{passed} exercices réussis sur {total}",
  "dash.inProgress": "{n} en cours",
  "dash.continue": "Continuer · Unité {n}",
  "dash.start": "Commencer le cours · Unité 1",
  "dash.allDonePre": "Toutes les unités sont terminées — place à l’",
  "dash.mockLink": "examen blanc",
  "dash.upNext": "À suivre : l’unité {n} a des exercices inachevés.",
  "dash.exercises": "{passed}/{total} exercices",
  "dash.mockAttempts": "Tentatives d’examen blanc : {n} (dernière : {date})",
  "dash.mockNone": "Examen blanc pas encore tenté.",
  "dash.resetAll": "Réinitialiser toute la progression",
  "dash.resetConfirm": "Réinitialiser TOUTE la progression ? Cela efface les résultats des exercices, la liste de contrôle et l’historique des examens blancs.",
  "dash.mockHistory": "Historique des examens blancs",
  "th.date": "Date",
  "th.listening": "Compréhension orale",
  "th.readingA": "Compréhension écrite A",
  "th.readingB": "Compréhension écrite B",
  "th.writing": "Expression écrite",
  "th.speaking": "Expression orale",
  "chklist.title": "Liste d’auto-évaluation A1",
  "chklist.intro": "Cochez ce que vous savez faire avec assurance. Toutes les cases cochées = vous êtes prêt à vous inscrire à l’examen.",
  "ipa.tab": "Référence de prononciation API",
  "ipa.tabShort": "API /ə/",
  "ipa.quick": "Aide-mémoire API",
  "ipa.full": "Guide complet",
  "glos.full": "Page complète",
  "buy.opening": "Ouverture du paiement…",
  "buy.buy": "Acheter le cours · {price}",
  "buy.errStart": "Impossible de démarrer le paiement. Veuillez réessayer.",
  "buy.errLoad": "Impossible de charger le paiement. Veuillez réessayer.",
  "buy.errConn": "Impossible de démarrer le paiement. Veuillez vérifier votre connexion et réessayer.",
  "pw.locked": "VERROUILLÉ",
  "pw.partOfFull": "{what} fait partie du cours complet",
  "pw.oneTime": "Un seul paiement de {price} débloque tout, pour toujours : les {units} unités, l’examen blanc avec minuteurs, le glossaire complet et le suivi de progression sur tous vos appareils.",
  "pw.alreadyBought": "Déjà acheté ? Connectez-vous",
  "pw.notSure": "Vous hésitez encore ?",
  "pw.tryFree": "Essayez l’unité {n} gratuitement",
  "pw.noAccount": "— aucun compte requis.",
  "what.glossary": "Le glossaire",
  "what.mock": "L’examen blanc",
  "banner.preview": "Vous consultez l’<b>aperçu gratuit</b>. Vos réponses sont enregistrées sur cet appareil",
  "banner.previewKeep": " — créez un compte pour les conserver",
  "mock.head": "Examen blanc · A1",
  "mock.title": "Examen d’entraînement complet",
  "mock.conditions": "Conditions d’examen",
  "mock.conditionsNote": " — afficher les minuteurs par épreuve (15 / 30 / 30 / 10 min). À la fin du temps, l’épreuve est marquée « hors délai », mais vous pouvez terminer.",
  "mock.p1title": "Épreuve 1 · Comprensió oral (compréhension orale) — 15 min",
  "mock.p2title": "Épreuve 2 · Comprensió lectora (compréhension écrite) — 30 min",
  "mock.p3title": "Épreuve 3 · Expressió escrita (expression écrite) — 30 min",
  "mock.p4title": "Épreuve 4 · Expressió oral (expression orale) — 10 min",
  "mock.timerReset": "Réinitialiser le minuteur",
  "mock.timerStart": "Démarrer le minuteur de {mins} min",
  "mock.p1note": "Le texte est lu à voix haute <b>deux fois</b> avec une pause, à l’aide de la voix catalane de votre navigateur. Ne le lisez pas — écoutez simplement, puis répondez.",
  "mock.play": "▶ Lire le texte audio (deux fois)",
  "mock.stop": "■ Arrêter",
  "mock.playP1": "Lecture — première écoute…",
  "mock.playPause": "Pause… la deuxième écoute commence dans 5 s",
  "mock.playP2": "Lecture — deuxième écoute…",
  "mock.showScript": "Afficher le texte",
  "mock.taskA2": "Tâche A — Lisez cet avis et répondez.",
  "mock.answers": "Réponses",
  "mock.showAnswers": "Afficher les réponses",
  "mock.taskB2": "Tâche B — Associez chaque panneau (1–5) à sa signification (a–e).",
  "mock.taskA3": "Tâche A — Remplissez cette demande de carte de bibliothèque vous concernant.",
  "mock.p3ph": "Écrivez votre carte postale ici (35–45 mots)…",
  "mock.words": "Mots :",
  "mock.model38": "Modèle (38 mots)",
  "mock.part1p4": "Partie 1 — Répondez à ces questions à voix haute par des phrases complètes (la série classique de l’examinateur) :",
  "mock.modelP1": "Réponses modèles (Partie 1)",
  "mock.roleSkeleton": "Trame de jeu de rôle",
  "mock.saveTitle": "Enregistrer cette tentative",
  "mock.saveNote": "Termine la session et enregistre les résultats par épreuve (avec la date du jour) dans votre navigateur.",
  "mock.finishSave": "Terminer et enregistrer la tentative",
  "mock.saved": "Tentative enregistrée.",
  "mock.history": "Historique des tentatives",
  "mock.noAttempts": "Aucune tentative enregistrée pour l’instant.",
  "mock.thP1": "É1 compr. orale",
  "mock.thP2": "É2 compr. écrite",
  "mock.thP3": "É3 expr. écrite",
  "mock.thP4": "É4 expr. orale",
  "mock.overTime": " hors délai",
  "mock.selfPassed": "auto-validé",
  "mock.notYet": "pas encore",
  "mock.wordsAbbr": "m.",
  "mock.aloud": "à voix haute",
};

const ru: Strings = {
  "nav.home": "Главная и прогресс",
  "nav.ipa": "Руководство по МФА",
  "nav.exam": "Официальный экзамен",
  "nav.mock": "Пробный экзамен",
  "nav.glossary": "Глоссарий",
  "nav.unit": "Раздел {n}",
  "nav.getFull": "Получить полный курс",
  "nav.getCourse": "Получить курс",
  "nav.allCourses": "Все курсы",
  "nav.account": "Аккаунт и покупки",
  "nav.admin": "Панель администратора",
  "nav.myCourses": "Мои курсы и прогресс",
  "auth.login": "Войти",
  "auth.signout": "Выйти",
  "ui.explainedIn": "Объяснение на",
  "a11y.locked": "Заблокировано",
  "a11y.expand": "Развернуть меню курса",
  "a11y.collapse": "Свернуть меню курса",
  "a11y.courseNav": "Навигация по курсу",
  "a11y.courseHome": "Главная курса",
  "a11y.allCourses": "Verbadium — все курсы",
  "a11y.courseMenu": "Меню курса",
  "a11y.accountMenu": "Меню аккаунта",
  "a11y.close": "Закрыть",
  "a11y.playAudio": "Воспроизвести аудио {n}",
  "ex.section": "Упражнения",
  "ex.modelAnswer": "Образец ответа",
  "ex.note": "Примечание",
  "ex.personalNote": "Личные ответы — заполните их для подготовки к экзамену.",
  "glos.heading": "Глоссарий: все слова курса",
  "glos.intro": "По алфавиту (артикли не учитываются). Р. = раздел, где слово вводится впервые. Произношение — центральнокаталанское, МФА. Нажмите на заголовок столбца для сортировки; нажмите 🔊, чтобы прослушать слово.",
  "glos.searchPh": "Поиск по глоссарию…",
  "glos.entries": "записей",
  "glos.listen": "Прослушать",
  "glos.subject": "Каталанский",
  "glos.ipa": "МФА",
  "glos.unitCol": "Р.",
  "ex.done": "✓ выполнено",
  "ex.tried": "начато",
  "btn.check": "Проверить ответы",
  "btn.showCorrect": "Показать правильные ответы",
  "btn.showModel": "Показать образец ответа",
  "btn.showModels": "Показать образцы ответов",
  "btn.showCatalan": "Показать каталанский",
  "btn.retry": "Повторить",
  "sm.gotIt": "✓ Понятно",
  "sm.notYet": "✗ Ещё нет",
  "sm.done": "✓ Готово",
  "tf.true": "Верно",
  "tf.false": "Неверно",
  "fb.accents": "✓ (проверьте надстрочные знаки!)",
  "score.perfect": "perfecte!",
  "ph.inCatalan": "…по-каталански",
  "ph.inMeaning": "…по-русски",
  "ph.writeHere": "Пишите здесь…",
  "chk.aloud": "Я произнёс это вслух",
  "dash.progress": "Ваш прогресс",
  "dash.passed": "Пройдено упражнений: {passed} из {total}",
  "dash.inProgress": "{n} в процессе",
  "dash.continue": "Продолжить · Раздел {n}",
  "dash.start": "Начать курс · Раздел 1",
  "dash.allDonePre": "Все разделы завершены — время для ",
  "dash.mockLink": "пробного экзамена",
  "dash.upNext": "Далее: в разделе {n} есть незавершённые упражнения.",
  "dash.exercises": "{passed}/{total} упражнений",
  "dash.mockAttempts": "Попыток пробного экзамена: {n} (последняя: {date})",
  "dash.mockNone": "Пробный экзамен ещё не проходился.",
  "dash.resetAll": "Сбросить весь прогресс",
  "dash.resetConfirm": "Сбросить ВЕСЬ прогресс? Это очистит результаты упражнений, список самопроверки и историю пробных экзаменов.",
  "dash.mockHistory": "История пробных экзаменов",
  "th.date": "Дата",
  "th.listening": "Аудирование",
  "th.readingA": "Чтение A",
  "th.readingB": "Чтение B",
  "th.writing": "Письмо",
  "th.speaking": "Говорение",
  "chklist.title": "Чек-лист самооценки A1",
  "chklist.intro": "Отметьте то, что уверенно умеете. Все галочки = вы готовы записаться на экзамен.",
  "ipa.tab": "Справочник произношения МФА",
  "ipa.tabShort": "МФА /ə/",
  "ipa.quick": "Краткий справочник МФА",
  "ipa.full": "Полное руководство",
  "glos.full": "Полная страница",
  "buy.opening": "Открываем оплату…",
  "buy.buy": "Купить курс · {price}",
  "buy.errStart": "Не удалось начать оплату. Попробуйте ещё раз.",
  "buy.errLoad": "Не удалось загрузить оплату. Попробуйте ещё раз.",
  "buy.errConn": "Не удалось начать оплату. Проверьте соединение и попробуйте ещё раз.",
  "pw.locked": "ЗАБЛОКИРОВАНО",
  "pw.partOfFull": "{what} входит в полный курс",
  "pw.oneTime": "Один платёж {price} навсегда открывает всё: все разделы ({units}), пробный экзамен с таймерами, полный глоссарий и отслеживание прогресса на всех ваших устройствах.",
  "pw.alreadyBought": "Уже купили? Войдите",
  "pw.notSure": "Ещё не уверены?",
  "pw.tryFree": "Попробуйте раздел {n} бесплатно",
  "pw.noAccount": "— аккаунт не нужен.",
  "what.glossary": "Глоссарий",
  "what.mock": "Пробный экзамен",
  "banner.preview": "Вы просматриваете <b>бесплатный предпросмотр</b>. Ваши ответы сохраняются на этом устройстве",
  "banner.previewKeep": " — создайте аккаунт, чтобы сохранить их",
  "mock.head": "Пробный экзамен · A1",
  "mock.title": "Полный пробный экзамен",
  "mock.conditions": "Экзаменационные условия",
  "mock.conditionsNote": " — показывать таймеры по частям (15 / 30 / 30 / 10 мин). Когда время выходит, часть помечается как «просрочено», но вы можете её закончить.",
  "mock.p1title": "Часть 1 · Comprensió oral (аудирование) — 15 мин",
  "mock.p2title": "Часть 2 · Comprensió lectora (чтение) — 30 мин",
  "mock.p3title": "Часть 3 · Expressió escrita (письмо) — 30 мин",
  "mock.p4title": "Часть 4 · Expressió oral (говорение) — 10 мин",
  "mock.timerReset": "Сбросить таймер",
  "mock.timerStart": "Запустить таймер на {mins} мин",
  "mock.p1note": "Текст зачитывается вслух <b>дважды</b> с паузой, используя каталанский голос вашего браузера. Не читайте его — просто слушайте, затем отвечайте.",
  "mock.play": "▶ Воспроизвести текст для аудирования (дважды)",
  "mock.stop": "■ Стоп",
  "mock.playP1": "Воспроизведение — первое чтение…",
  "mock.playPause": "Пауза… второе чтение начнётся через 5 с",
  "mock.playP2": "Воспроизведение — второе чтение…",
  "mock.showScript": "Показать текст",
  "mock.taskA2": "Задание A — Прочитайте это объявление и ответьте.",
  "mock.answers": "Ответы",
  "mock.showAnswers": "Показать ответы",
  "mock.taskB2": "Задание B — Сопоставьте каждый знак (1–5) с его значением (a–e).",
  "mock.taskA3": "Задание A — Заполните эту заявку на читательский билет о себе.",
  "mock.p3ph": "Напишите свою открытку здесь (35–45 слов)…",
  "mock.words": "Слов:",
  "mock.model38": "Образец (38 слов)",
  "mock.part1p4": "Часть 1 — Ответьте на это вслух полными предложениями (классический набор экзаменатора):",
  "mock.modelP1": "Образцы ответов (Часть 1)",
  "mock.roleSkeleton": "Шаблон ролевой игры",
  "mock.saveTitle": "Сохранить эту попытку",
  "mock.saveNote": "Завершает сдачу и сохраняет результаты по частям (с сегодняшней датой) в вашем браузере.",
  "mock.finishSave": "Завершить и сохранить попытку",
  "mock.saved": "Попытка сохранена.",
  "mock.history": "История попыток",
  "mock.noAttempts": "Пока нет сохранённых попыток.",
  "mock.thP1": "Ч1 аудирование",
  "mock.thP2": "Ч2 чтение",
  "mock.thP3": "Ч3 письмо",
  "mock.thP4": "Ч4 говорение",
  "mock.overTime": " просрочено",
  "mock.selfPassed": "зачтено",
  "mock.notYet": "ещё нет",
  "mock.wordsAbbr": "сл.",
  "mock.aloud": "вслух",
};

const de: Strings = {
  "nav.home": "Start & Fortschritt",
  "nav.ipa": "IPA-Leitfaden",
  "nav.exam": "Die offizielle Prüfung",
  "nav.mock": "Probeprüfung",
  "nav.glossary": "Glossar",
  "nav.unit": "Einheit {n}",
  "nav.getFull": "Vollständigen Kurs holen",
  "nav.getCourse": "Kurs holen",
  "nav.allCourses": "Alle Kurse",
  "nav.account": "Konto & Käufe",
  "nav.admin": "Admin-Dashboard",
  "nav.myCourses": "Meine Kurse & Fortschritt",
  "auth.login": "Anmelden",
  "auth.signout": "Abmelden",
  "ui.explainedIn": "Erklärt auf",
  "a11y.locked": "Gesperrt",
  "a11y.expand": "Kursmenü ausklappen",
  "a11y.collapse": "Kursmenü einklappen",
  "a11y.courseNav": "Kursnavigation",
  "a11y.courseHome": "Kursstart",
  "a11y.allCourses": "Verbadium — alle Kurse",
  "a11y.courseMenu": "Kursmenü",
  "a11y.accountMenu": "Kontomenü",
  "a11y.close": "Schließen",
  "a11y.playAudio": "Audio {n} abspielen",
  "ex.section": "Übungen",
  "ex.modelAnswer": "Musterantwort",
  "ex.note": "Hinweis",
  "ex.personalNote": "Persönliche Antworten — fülle sie als Prüfungsübung aus.",
  "glos.heading": "Glossar: jedes Wort in diesem Kurs",
  "glos.intro": "Alphabetisch (Artikel werden ignoriert). E. = die Einheit, in der das Wort zuerst eingeführt wird. Aussprache in Zentralkatalanisch, IPA. Klicke auf eine Spaltenüberschrift zum Sortieren; klicke auf 🔊, um das Wort zu hören.",
  "glos.searchPh": "Im Glossar suchen…",
  "glos.entries": "Einträge",
  "glos.listen": "Anhören",
  "glos.subject": "Katalanisch",
  "glos.ipa": "IPA",
  "glos.unitCol": "E.",
  "ex.done": "✓ erledigt",
  "ex.tried": "versucht",
  "btn.check": "Antworten prüfen",
  "btn.showCorrect": "Richtige Antworten anzeigen",
  "btn.showModel": "Musterantwort anzeigen",
  "btn.showModels": "Musterantworten anzeigen",
  "btn.showCatalan": "Katalanisch anzeigen",
  "btn.retry": "Erneut versuchen",
  "sm.gotIt": "✓ Verstanden",
  "sm.notYet": "✗ Noch nicht",
  "sm.done": "✓ Fertig",
  "tf.true": "Richtig",
  "tf.false": "Falsch",
  "fb.accents": "✓ (achte auf die Akzente!)",
  "score.perfect": "perfecte!",
  "ph.inCatalan": "…auf Katalanisch",
  "ph.inMeaning": "…auf Deutsch",
  "ph.writeHere": "Hier schreiben…",
  "chk.aloud": "Ich habe es laut gesagt",
  "dash.progress": "Dein Fortschritt",
  "dash.passed": "{passed} von {total} Übungen bestanden",
  "dash.inProgress": "{n} in Bearbeitung",
  "dash.continue": "Fortsetzen · Einheit {n}",
  "dash.start": "Kurs starten · Einheit 1",
  "dash.allDonePre": "Alle Einheiten abgeschlossen — Zeit für die ",
  "dash.mockLink": "Probeprüfung",
  "dash.upNext": "Als Nächstes: Einheit {n} hat noch offene Übungen.",
  "dash.exercises": "{passed}/{total} Übungen",
  "dash.mockAttempts": "Versuche der Probeprüfung: {n} (letzter: {date})",
  "dash.mockNone": "Probeprüfung noch nicht versucht.",
  "dash.resetAll": "Gesamten Fortschritt zurücksetzen",
  "dash.resetConfirm": "ALLEN Fortschritt zurücksetzen? Dies löscht Übungsergebnisse, die Checkliste und den Verlauf der Probeprüfung.",
  "dash.mockHistory": "Verlauf der Probeprüfung",
  "th.date": "Datum",
  "th.listening": "Hören",
  "th.readingA": "Lesen A",
  "th.readingB": "Lesen B",
  "th.writing": "Schreiben",
  "th.speaking": "Sprechen",
  "chklist.title": "A1-Selbsteinschätzungs-Checkliste",
  "chklist.intro": "Hake ab, was du sicher kannst. Alle Kästchen angehakt = du bist bereit, dich für die Prüfung anzumelden.",
  "ipa.tab": "IPA-Aussprachereferenz",
  "ipa.tabShort": "IPA /ə/",
  "ipa.quick": "IPA-Kurzreferenz",
  "ipa.full": "Vollständiger Leitfaden",
  "glos.full": "Ganze Seite",
  "buy.opening": "Kasse wird geöffnet…",
  "buy.buy": "Kurs kaufen · {price}",
  "buy.errStart": "Kasse konnte nicht gestartet werden. Bitte versuche es erneut.",
  "buy.errLoad": "Kasse konnte nicht geladen werden. Bitte versuche es erneut.",
  "buy.errConn": "Kasse konnte nicht gestartet werden. Bitte prüfe deine Verbindung und versuche es erneut.",
  "pw.locked": "GESPERRT",
  "pw.partOfFull": "{what} ist Teil des vollständigen Kurses",
  "pw.oneTime": "Eine einmalige Zahlung von {price} schaltet alles dauerhaft frei: alle {units} Einheiten, die Probeprüfung mit Timern, das vollständige Glossar und die Fortschrittsverfolgung auf allen deinen Geräten.",
  "pw.alreadyBought": "Schon gekauft? Anmelden",
  "pw.notSure": "Noch unsicher?",
  "pw.tryFree": "Einheit {n} kostenlos testen",
  "pw.noAccount": "— kein Konto nötig.",
  "what.glossary": "Das Glossar",
  "what.mock": "Die Probeprüfung",
  "banner.preview": "Du siehst die <b>kostenlose Vorschau</b>. Deine Antworten werden auf diesem Gerät gespeichert",
  "banner.previewKeep": " — erstelle ein Konto, um sie zu behalten",
  "mock.head": "Probeprüfung · A1",
  "mock.title": "Vollständige Übungsprüfung",
  "mock.conditions": "Prüfungsbedingungen",
  "mock.conditionsNote": " — Timer pro Teil anzeigen (15 / 30 / 30 / 10 Min.). Wenn die Zeit abläuft, wird der Teil als „überzogen“ markiert, du kannst ihn aber beenden.",
  "mock.p1title": "Teil 1 · Comprensió oral (Hörverstehen) — 15 Min.",
  "mock.p2title": "Teil 2 · Comprensió lectora (Leseverstehen) — 30 Min.",
  "mock.p3title": "Teil 3 · Expressió escrita (schriftlicher Ausdruck) — 30 Min.",
  "mock.p4title": "Teil 4 · Expressió oral (mündlicher Ausdruck) — 10 Min.",
  "mock.timerReset": "Timer zurücksetzen",
  "mock.timerStart": "{mins}-Min.-Timer starten",
  "mock.p1note": "Der Text wird mit einer Pause <b>zweimal</b> vorgelesen, mit der katalanischen Stimme deines Browsers. Lies ihn nicht — höre einfach zu und antworte dann.",
  "mock.play": "▶ Hörtext abspielen (zweimal)",
  "mock.stop": "■ Stopp",
  "mock.playP1": "Wird abgespielt — erstes Vorlesen…",
  "mock.playPause": "Pause… zweites Vorlesen beginnt in 5 s",
  "mock.playP2": "Wird abgespielt — zweites Vorlesen…",
  "mock.showScript": "Text anzeigen",
  "mock.taskA2": "Aufgabe A — Lies diesen Hinweis und antworte.",
  "mock.answers": "Antworten",
  "mock.showAnswers": "Antworten anzeigen",
  "mock.taskB2": "Aufgabe B — Ordne jedes Schild (1–5) seiner Bedeutung (a–e) zu.",
  "mock.taskA3": "Aufgabe A — Fülle diesen Bibliotheksausweis-Antrag mit deinen eigenen Angaben aus.",
  "mock.p3ph": "Schreibe deine Postkarte hier (35–45 Wörter)…",
  "mock.words": "Wörter:",
  "mock.model38": "Muster (38 Wörter)",
  "mock.part1p4": "Teil 1 — Beantworte diese Fragen laut in ganzen Sätzen (der klassische Fragenkatalog des Prüfers):",
  "mock.modelP1": "Musterantworten (Teil 1)",
  "mock.roleSkeleton": "Gerüst für das Rollenspiel",
  "mock.saveTitle": "Diesen Versuch speichern",
  "mock.saveNote": "Beendet die Sitzung und speichert die Ergebnisse pro Teil (mit dem heutigen Datum) in deinem Browser.",
  "mock.finishSave": "Beenden & Versuch speichern",
  "mock.saved": "Versuch gespeichert.",
  "mock.history": "Versuchsverlauf",
  "mock.noAttempts": "Noch keine Versuche gespeichert.",
  "mock.thP1": "T1 Hören",
  "mock.thP2": "T2 Lesen",
  "mock.thP3": "T3 Schreiben",
  "mock.thP4": "T4 Sprechen",
  "mock.overTime": " überzogen",
  "mock.selfPassed": "selbst bestanden",
  "mock.notYet": "noch nicht",
  "mock.wordsAbbr": "W.",
  "mock.aloud": "laut",
};

export const UI: Record<Locale, Strings> = { en, es, ca: en, fr, ru, de };

/** Translate a chrome key for a locale, with {placeholder} interpolation and
    English fallback. */
export function tUI(locale: Locale, key: string, vars?: Record<string, string | number>): string {
  return interpolate(UI[locale]?.[key] ?? en[key] ?? key, vars);
}

/** The full chrome dictionary for one locale, English-filled. Handed to the
    client provider so the browser only ever receives the active locale. */
export function uiDict(locale: Locale): Strings {
  return locale === 'en' ? en : { ...en, ...UI[locale] };
}

/** The chrome strings <BuyButton> needs, resolved for a locale. Lets that
    client component take a small prop instead of importing this whole map. */
export function buyLabels(locale: Locale): BuyLabels {
  return {
    errStart: tUI(locale, 'buy.errStart'),
    errLoad: tUI(locale, 'buy.errLoad'),
    errConn: tUI(locale, 'buy.errConn'),
    opening: tUI(locale, 'buy.opening'),
    buy: tUI(locale, 'buy.buy'),   // template, still contains {price}
  };
}
